INSERT INTO recruiters
(position, city, state, qualifications, recruiter, status)
VALUES
("Account Manager/DRD", "Portland", "Maine", "Do you have B2B sales experience?", "Unassigned", "on"),
("Account Manager/DRD", "Baltimore", "Maryland", "Do you have B2B sales experience?", "Unassigned", "on"),
("Account Manager/DRD", "Dedham", "Massachusetts", "Do you have B2B sales experience?", "Unassigned", "on"),
("Account Manager/DRD", "Rochester", "New York", "Do you have B2B sales experience?", "Unassigned", "on"),
("Account Manager/DRD", "Charlotte", "North Carolina", "Do you have B2B sales experience?", "Unassigned", "on"),
("Account Manager/DRD", "Philadelphia", "Pennsylvania", "Do you have B2B sales experience?", "Unassigned", "on"),
("Driver/Phlebotomist", "Bloomington", "Indiana", "Do you have a CDL?", "karen.whitford@redcross.org", "on"),
("Driver/Phlebotomist", "Ft Wayne", "Indiana", "Do you have a CDL?", "karen.whitford@redcross.org", "on"),
("Driver/Phlebotomist", "Merrillville", "Indiana", "Do you have a CDL?", "karen.whitford@redcross.org", "on"),
("Driver/Phlebotomist", "Wichita", "Kansas", "Do you have a CDL?", "rachel.sprague@redcross.org", "on"),
("Driver/Phlebotomist", "All cities", "Maine", "Do you have a CDL?", "bethann.stanek2@redcross.org", "on"),
("Driver/Phlebotomist", "St. Paul", "Minnesota", "Do you have a CDL?", "amy.nighswander@redcross.org", "on"),
("Driver/Phlebotomist", "Columbia", "Missouri", "Do you have a CDL?", "cynthia.ferris@redcross.org", "on"),
("Driver/Phlebotomist", "Kansas City", "Missouri", "Do you have a CDL?", "cynthia.ferris@redcross.org", "on"),
("Driver/Phlebotomist", "St Louis", "Missouri", "Do you have a CDL?", "cynthia.ferris@redcross.org", "on"),
("Driver/Phlebotomist", "Omaha", "Nebraska", "Do you have a CDL?", "rachel.sprague@redcross.org", "on"),
("Driver/Phlebotomist", "All cities", "New Hampshire", "Do you have a CDL?", "amanda.cunningham@redcross.org", "on"),
("Driver/Phlebotomist", "All cities", "North Carolina", "Do you have a CDL?", "jacqueline.garcia@redcross.org", "on"),
("Driver/Phlebotomist", "Cleveland", "Ohio", "Do you have a CDL?", "cynthia.ferris@redcross.org", "on"),
("Driver/Phlebotomist", "Columbus", "Ohio", "Do you have a CDL?", "karen.whitford@redcross.org", "on"),
("Driver/Phlebotomist", "Toledo", "Ohio", "Do you have a CDL?", "cynthia.ferris@redcross.org", "on"),
("Driver/Phlebotomist", "Portland", "Oregon", "Do you have a CDL?", "dena.gray@redcross.org", "on"),
("Driver/Phlebotomist", "Columbia", "South Carolina", "Do you have a CDL?", "jacqueline.garcia@redcross.org", "on"),
("Driver/Phlebotomist", "All cities", "Vermont", "Do you have a CDL?", "bethann.stanek2@redcross.org", "on"),
("Driver/Phlebotomist", "Richmond", "Virginia", "Do you have a CDL?", "jennifer.holland@redcross.org", "on"),
("Driver/Phlebotomist", "Roanoke", "Virginia", "Do you have a CDL?", "jennifer.holland@redcross.org", "on"),
("Medical Technologist", "Oakland", "California", "What certifications/licenses do you have? Do you hold any state license?", "sara.sutherland@redcross.org", "on"),
("Medical Technologist", "Pomona", "California", "What certifications/licenses do you have? Do you hold any state license?", "sara.sutherland@redcross.org", "on"),
("Medical Technologist", "Farmington", "Connecticut", "What certifications/licenses do you have? Do you hold any state license?", "maurice.stuart@redcross.org", "on"),
("Medical Technologist", "Atlanta", "Georgia", "What certifications/licenses do you have? Do you hold any state license?", "niki.bratchette@redcross.org", "on"),
("Medical Technologist", "Dedham", "Massachusetts", "What certifications/licenses do you have? Do you hold any state license?", "maurice.stuart@redcross.org", "on"),
("Medical Technologist", "St Louis", "Missouri", "What certifications/licenses do you have? Do you hold any state license?", "linda.lopatin@redcross.org", "on"),
("Medical Technologist", "Omaha", "Nebraska", "What certifications/licenses do you have? Do you hold any state license?", "sara.sutherland@redcross.org", "on"),
("Medical Technologist", "W. Henrietta", "New York", "What certifications/licenses do you have? Do you hold any state license?", "maurice.stuart@redcross.org", "on"),
("Medical Technologist", "Tulsa", "Oklahoma", "What certifications/licenses do you have? Do you hold any state license?", "sara.sutherland@redcross.org", "on"),
("Medical Technologist", "Philadelphia", "Pennsylvania", "What certifications/licenses do you have? Do you hold any state license?", "susan.kelly@redcross.org", "on"),
("Medical Technologist", "Richmond", "Virginia", "What certifications/licenses do you have? Do you hold any state license?", "maurice.stuart@redcross.org", "on"),
("Medical Technologist", "Virginia Beach", "Virginia", "What certifications/licenses do you have? Do you hold any state license?", "maurice.stuart@redcross.org", "on"),
("Nurse", "Oakland", "California", "Are you a state-licensed RN or LPN?", "dena.gray@redcross.org", "on"),
("Nurse", "Pomona", "California", "Are you a state-licensed RN or LPN?", "dena.gray@redcross.org", "on"),
("Nurse", "Sacramento", "California", "Are you a state-licensed RN or LPN?", "dena.gray@redcross.org", "on"),
("Nurse", "Wichita", "Kansas", "Can you work a variable schedule?", "rachel.sprague@redcross.org", "on"),
("Nurse", "Omaha", "Nebraska", "Can you work a variable schedule?", "rachel.sprague@redcross.org", "on"),
("Nurse", "Durham", "North Carolina", "Are you a state-licensed RN or LPN?", "Unassigned", "on"),
("Nurse", "Portland", "Oregon", "Are you a state-licensed RN or LPN?", "dena.gray@redcross.org", "on"),
("Nurse", "Columbia", "South Carolina", "Are you a state-licensed RN or LPN?", "ardie.gipson@redcross.org", "on"),
("Phlebotomist", "Pomona", "California", "Can you work a variable schedule?", "dena.gray@redcross.org", "on"),
("Phlebotomist", "Boise", "Idaho", "Can you work a variable schedule?", "Unassigned", "on"),
("Phlebotomist", "Wichita", "Kansas", "Can you work a variable schedule?", "rachel.sprague@redcross.org", "on"),
("Phlebotomist", "All cities", "Maryland", "Can you work a variable schedule?", "jacqueline.garcia@redcross.org", "on"),
("Phlebotomist", "All cities", "Michigan", "Can you work a variable schedule?", "karen.whitford@redcross.org", "on"),
("Phlebotomist", "Mankato", "Minnesota", "Can you work a variable schedule?", "amy.nighswander@redcross.org", "on"),
("Phlebotomist", "St. Paul", "Minnesota", "Can you work a variable schedule?", "amy.nighswander@redcross.org", "on"),
("Phlebotomist", "Missoula", "Montana", "Can you work a variable schedule?", "Unassigned", "on"),
("Phlebotomist", "Omaha", "Nebraska", "Can you work a variable schedule?", "rachel.sprague@redcross.org", "on"),
("Phlebotomist", "Nutley", "New Jersey", "Can you work a variable schedule?", "jennifer.holland@redcross.org", "on"),
("Phlebotomist", "All cities", "North Carolina", "Can you work a variable schedule?", "jacqueline.garcia@redcross.org", "on"),
("Phlebotomist", "All cities", "Ohio", "Can you work a variable schedule?", "karen.whitford@redcross.org", "on"),
("Phlebotomist", "Portland", "Oregon", "Can you work a variable schedule?", "dena.gray@redcross.org", "on"),
("Phlebotomist", "Collegeville", "Pennsylvania", "Can you work a variable schedule?", "natasha.baylor@redcross.org", "on"),
("Phlebotomist", "Nashville", "Tennessee", "Can you work a variable schedule?", "nick.bays@redcross.org", "on"),
("Phlebotomist", "Salt Lake City", "Utah", "Can you work a variable schedule?", "natasha.baylor@redcross.org", "on"),
("Phlebotomist", "All cities", "Virginia", "Can you work a variable schedule?", "jennifer.holland@redcross.org", "on"),
("Phlebotomist", "Richmond", "Virginia", "Can you work a variable schedule?", "jennifer.holland@redcross.org", "on");