INSERT INTO recruiters
(position, city, state, state_name, qualifications, recruiter, region, status)
VALUES
("Clinical Services Nurse Specialist", "Columbia", "SC", "South Carolina", "Must be an RN, do you have Apheresis experience", "ardie.gipson@redcross.org", "East", "on"),
("Driver/Phlebotomist", "Wichita", "KS", "Kansas", "Can you work a variable schedule, Do you have CDL Class A or CDL Class B with Airbrakes", "rachel.sprague@redcross.org", "West", "on"),
("Driver/Phlebotomist", "Omaha", "NE", "Nebraska", "Can you work a variable schedule, Do you have CDL Class A or CDL Class B with Airbrakes", "rachel.sprague@redcross.org", "West", "on"),
("Driver/Phlebotomist", "Bloomington ", "IN", "Indiana", "Do you have CDL", "karen.whitford@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Ft Wayne", "IN", "Indiana", "Do you have CDL", "karen.whitford@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Merrillville", "IN", "Indiana", "Do you have CDL", "karen.whitford@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "All", "ME", "Maine", "Do you have CDL", "bethann.stanek2@redcross.org ", "East", "on"),
("Driver/Phlebotomist", "St. Paul", "MN", "Minnesota", "Do you have CDL", "amy.nighswander@redcross.org", "West", "on"),
("Driver/Phlebotomist", "St Louis", "MO", "Missouri", "Do you have CDL", "cynthia.ferris@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Kansas City", "MO", "Missouri", "Do you have CDL", "cynthia.ferris@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Columbia", "MO", "Missouri", "Do you have CDL", "cynthia.ferris@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "All", "NC", "North Carolina", "Do you have CDL", "jacqueline.garcia@redcross.org", "East", "on"),
("Driver/Phlebotomist", "All", "NH", "New Hampshire", "Do you have CDL", "amanda.cunningham@redcross.org", "East", "on"),
("Driver/Phlebotomist", "Cleveland", "OH", "Ohio", "Do you have CDL", "cynthia.ferris@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Toledo", "OH", "Ohio", "Do you have CDL", "cynthia.ferris@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Columbus", "OH", "Ohio", "Do you have CDL", "karen.whitford@redcross.org", "Central", "on"),
("Driver/Phlebotomist", "Portland", "OR", "Oregon", "Do you have CDL", "dena.gray@redcross.org", "West", "on"),
("Driver/Phlebotomist", "Columbia", "SC", "South Carolina", "Do you have CDL", "jacqueline.garcia@redcross.org", "East", "on"),
("Driver/Phlebotomist", "Richmond", "VA", "Virginia", "Do you have CDL", "jennifer.holland@redcross.org", "East", "on"),
("Driver/Phlebotomist", "Roanoke", "VA", "Virginia", "Do you have CDL", "jennifer.holland@redcross.org", "East", "on"),
("Driver/Phlebotomist", "All", "VT", "Vermont", "Do you have CDL", "bethann.stanek2@redcross.org ", "East", "on"),
("Medical Technologist", "Oakland", "CA", "California", "What certifications/licenses do you have?  Do you hold any state license?", "sara.sutherland@redcross.org", "West", "on"),
("Medical Technologist", "Pomona", "CA", "California", "What certifications/licenses do you have?  Do you hold any state license?", "sara.sutherland@redcross.org", "West", "on"),
("Medical Technologist", "Farmington", "CT", "Connecticut", "What certifications/licenses do you have?  Do you hold any state license?", "maurice.stuart@redcross.org", "East", "on"),
("Medical Technologist", "Atlanta", "GA", "Georgia", "What certifications/licenses do you have?  Do you hold any state license?", "niki.bratchette@redcross.org ", "Central", "on"),
("Medical Technologist", "Dedham", "MA", "Massachusetts", "What certifications/licenses do you have?  Do you hold any state license?", "maurice.stuart@redcross.org", "East", "on"),
("Medical Technologist", "St Louis", "MO", "Missouri", "What certifications/licenses do you have?  Do you hold any state license?", "linda.lopatin@redcross.org", "Central", "on"),
("Medical Technologist", "Omaha", "NE", "Nebraska", "What certifications/licenses do you have?  Do you hold any state license?", "sara.sutherland@redcross.org", "West", "on"),
("Medical Technologist", "W. Henrietta", "NY", "New York", "What certifications/licenses do you have?  Do you hold any state license?", "maurice.stuart@redcross.org", "East", "on"),
("Medical Technologist", "Tulsa", "OK", "Oklahoma", "What certifications/licenses do you have?  Do you hold any state license?", "sara.sutherland@redcross.org", "West", "on"),
("Medical Technologist", "Richmond", "VA", "Virginia", "What certifications/licenses do you have?  Do you hold any state license?", "maurice.stuart@redcross.org", "East", "on"),
("Medical Technologist", "Virginia Beach", "VA", "Virginia", "What certifications/licenses do you have?  Do you hold any state license?", "maurice.stuart@redcross.org", "East", "on"),
("Nurse", "Oakland", "CA", "California", "Are you a state-licensed RN or LPN", "dena.gray@redcross.org", "West", "on"),
("Nurse", "Sacramento", "CA", "California", "Are you a state-licensed RN or LPN", "dena.gray@redcross.org", "West", "on"),
("Nurse", "Pomona", "CA", "California", "Are you a state-licensed RN or LPN", "dena.gray@redcross.org", "West", "on"),
("Nurse", "Portland", "OR", "Oregon", "Are you a state-licensed RN or LPN", "dena.gray@redcross.org", "West", "on"),
("Nurse", "Wichita", "KS", "Kansas", "Can you work a variable schedule", "rachel.sprague@redcross.org", "West", "on"),
("Nurse", "Omaha", "NE", "Nebraska", "Can you work a variable schedule", "rachel.sprague@redcross.org", "West", "on"),
("Phlebotomist", "Pomona", "CA", "California", "Can you work a variable schedule", "dena.gray@redcross.org", "West", "on"),
("Phlebotomist", "Wichita", "KS", "Kansas", "Can you work a variable schedule", "rachel.sprague@redcross.org", "West", "on"),
("Phlebotomist", "St. Paul", "MN", "Minnesota", "Can you work a variable schedule", "amy.nighswander@redcross.org", "West", "on"),
("Phlebotomist", "Mankato", "MN", "Minnesota", "Can you work a variable schedule", "amy.nighswander@redcross.org", "West", "on"),
("Phlebotomist", "All", "NC", "North Carolina", "Can you work a variable schedule", "jacqueline.garcia@redcross.org", "East", "on"),
("Phlebotomist", "Omaha", "NE", "Nebraska", "Can you work a variable schedule", "rachel.sprague@redcross.org", "West", "on"),
("Phlebotomist", "Nutley", "NJ", "New Jersey", "Can you work a variable schedule", "jennifer.holland@redcross.org", "East", "on"),
("Phlebotomist", "Portland", "OR", "Oregon", "Can you work a variable schedule", "dena.gray@redcross.org", "West", "on"),
("Phlebotomist", "Salt Lake City", "UT", "Utah", "Can you work a variable schedule", "natasha.baylor@redcross.org", "West", "on"),
("Phlebotomist", "Collegeville", "PA", "Pennsylvania", "Can you work a variable schedule", "natasha.baylor@redcross.org", "East", "on"),
("Phlebotomist", "", "MI", "Michigan", "Can you work a variable schedule", "karen.whitford@redcross.org", "Central", "on"),
("Phlebotomist", " ", "OH", "Ohio", "Can you work a variable schedule", "karen.whitford@redcross.org", "Central", "on"),
("Phlebotomist", "Nashville", "TN", "Tennessee", "Can you work a variable schedule", "nick.bays@redcross.org", "Central", "on"),
("Phlebotomist", "All", "MD", "Maryland", "Do you have CDL", "jacqueline.garcia@redcross.org", "East", "on"),
("Phlebotomist", "All", "VA", "Virginia", "Do you have CDL", "jennifer.holland@redcross.org", "East", "on"),
("Phlebotomist (PT)", "Richmond", "VA", "Virginia", "Can you work a variable schedule", "jennifer.holland@redcross.org", "East", "on"),
("Senior Lab Technologist", "Philadelphia", "PA", "Pennsylvania", "Do you have have BS degree in Biology or related field", "susan.kelly@redcross.org", "East", "on");